#! /usr/bin/env python

import genomon_pipeline
import genomon_pipeline.configure_if
import argparse

parser = argparse.ArgumentParser(prog = "genomon_pipeline")

parser.add_argument("--version", action = "version", version = "genomon_pipeline-" + genomon_pipeline.__version__)

parser.add_argument('analysis_type', choices=['dna', 'rna', 'germ'],
                    help = "analysis type")

parser.add_argument("sample_conf_file", metavar = "sample_conf.csv", default = None, type = str,
                    help = "input sample list flie [csv]")

parser.add_argument("project_root", metavar = "project_root_dir", default = None, type = str,
                    help = "output root directory")

parser.add_argument("genomon_conf_file", help = "config file for genomon pipeline", type = str)

parser.add_argument("--param_check", help = "only param check", action='store_true')
parser.add_argument("--disable_drmaa", help = "disable drmaa", action='store_true')
parser.add_argument("--multiprocess", help = "use ruffus multiprocess", default='100', type=int)
parser.add_argument("--verbose", help = "write messages to STDERR", default='3', type=int)
parser.add_argument("--retry_count", help = "retry count", type = int, default=0)

args = parser.parse_args()

genomon_pipeline.configure_if.main(args)

