#! /usr/bin/env python

from genomon_pipeline import __version__
import genomon_pipeline.runner
import argparse

parser = argparse.ArgumentParser(prog = "genomon_runner")

parser.add_argument("--version", action = "version", version = "genomon_runner-" + __version__)

parser.add_argument('script', metavar = "/path/to/singularity_bwa.sh", type = str, help = "input singularity script")
parser.add_argument("conf", metavar = "/path/to/sample.conf.yml", type = str, help = "input sample list flie [YAML]")
parser.set_defaults(handler=genomon_pipeline.runner.main)

args = parser.parse_args()

args.handler(args)
